#!/bin/bash

ignore-empty-password

image=~/Images/wonderegg/wondereggbridge.png
scaling=fill

indicator
indicator-radius=90=
indicator-thickness=13

fade-in=0.5
grace=0.8

font=Roboto
font-size=28

clock
timestr=%T
datestr=%F

effect-vignette=0.2:0.5

text-color=#cdd6f4
text-clear-color=#cdd6f4
text-caps-lock-color=#cdd6f4
text-ver-color=#cdd6f4
text-wrong-color=#cdd6f4

bs-hl-color=#f38ba8b3
caps-lock-bs-hl-color=#f38ba8b3
caps-lock-key=hl-color=#74c7ecb3
key-hl-color=#74c7ecb3

layout-bg-color=#00000000
layout-border-color=#00000000
layout-text-color=#00000000

line-color=#00000000
line-clear-color=#00000000
line-caps-lock-color=#00000000
line-ver-color=#00000000
line-wrong-color=#00000000

ring-color=#00000000
ring-clear-color=#00000000
ring-caps-lock-color=#00000000
ring-ver-color=#00000000
ring-wrong-color=#00000000

seperator-color=#00000000

inside-color=11111bb3
inside-clear-color=11111bb3
inside-caps-lock-color=11111bb3
inside-ver-color=11111bb3
inside-wrong-color=11111bb

