#!/bin/bash

if [ ! "$(pgrep "pipewire")" ]; then
	pipewire &
	pipewire-pulse &
	wireplumber &

fi

sxhkd &
udiskie --automount &

setxkbmap gb

bspc config border_width 			0
bspc config window_gap 				0

bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true

bspc config automatic_scheme 		dwindle

bspc monitor -d 1 2 3 4 5 6 7 8 9
