#!/bin/bash

if [ ! "$(pgrep "pipewire")" ]; then
	pipewire &
	pipewire-pulse &
	wireplumber &

fi

sxhkd &
udiskie --automount &

# set touchpad/mouse settings
xinput set-prop 'pointer-2-7-SynPS/2_Synaptics_TouchPad' 'libinput Accel Speed' -0.1
xinput set-prop 'Microsoft Microsoft 3-Button Mouse with IntelliEye(TM)' 'libinput Accel Speed' -0.3

setxkbmap gb

bspc config border_width 			0
bspc config window_gap 				0

bspc config split_ratio				0.5
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true

bspc config automatic_scheme 		dwindle

bspc monitor -d 1 2 3 4 5 6 7 8 9
