#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &
picom -b
./fehbg

bspc config border_width 			2
bspc config window_gap 				20

bspc config split_ratio				0.55
bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false

bspc config automatic_scheme 		dwindle

bspc rule -a Firefox desktop='^9'
