local options = {
    number = true,
    relativenumber = true,
    numberwidth = 4,
    expandtab = true,
    smarttab = true,
    shiftwidth = 4,
    tabstop = 4,
    softtabstop = 4,
    smartindent = true,
    autoindent = true,
    cindent = true,
    smartcase = true,
    ignorecase = true,
    fileencoding = "utf-8",
    encoding = "utf-8",
    backup = false,
    clipboard = "unnamedplus",
    writebackup = true,
    swapfile = false,
    completeopt = { "menu", "menuone", "noselect" },
    pumheight = 7,
    backspace = "indent,eol,start",
    undofile = true,
    mouse = "",
    mousemoveevent = false,
    cursorline = true,
    guicursor = 'n-v-c-sm:hor20,ci-ve:ver25,r-cr-o:block,i:ver25,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor',
    title = true,
    conceallevel = 0,
    hlsearch = true,
    showmode = false,
    laststatus = 2,
    showtabline = 0,
    splitbelow = true,
    splitright = true,
    termguicolors = true,
    timeoutlen = 100,
    updatetime = 300,
    wrap = true,
    list = true,
    splitkeep = "screen",
    fillchars = { eob = " ", foldopen = "", foldsep = " ", foldclose = "", lastline = " " },
    listchars = "tab:  ",
    foldenable = false,
    signcolumn = "yes",
    scrolloff = 20,
    cmdheight = 0,
}

for k, v in pairs(options) do
    vim.opt[k] = v
end
