#!/bin/bash

# set keyboard layout and gtk
gnomeschema=org.gnome.desktop.interface
gsettings set "$gnomeschema" cursor-theme Breeze_Obsidian
gsettings set "$gnomeschema" color-scheme "prefer-dark" color-scheme "prefer-dark"
gsettings set "$gnomeschema" gtk-theme "Catppuccin-Mocha-Standard-Sapphire-Dark"
gsettings set "$gnomeschema" icon-theme "Papirus-Dark"
gsettings set "$gnomeschema" font-name "UbuntuMono 11"
riverctl xcursor-theme Breeze_Obsidian 30

# change to whatever from riverctl list-inputs
trackpad="pointer-2-7-SynPS/2_Synaptics_TouchPad"
riverctl keyboard-layout gb
riverctl input "$trackpad" tap enabled
riverctl input "$trackpad" pointer-accel 0.1
riverctl input "$trackpad" natural-scroll disabled
riverctl input "$trackpad" disable-while-typing enabled
riverctl input "$trackpad" events disabled-on-external-mouse
riverctl input "$trackpad" accel-profile flat

mouse="pointer-1118-64-Microsoft_Microsoft_3-Button_Mouse_with_IntelliEye(TM)"
riverctl keyboard-layout gb
riverctl input "$mouse" tap enabled
riverctl input "$mouse" pointer-accel 0.1
riverctl input "$mouse" natural-scroll disabled
riverctl input "$mouse" disable-while-typing disabled
riverctl input "$mouse" accel-profile flat

# keybinds #################################################################
riverctl map normal Super+Shift Q exit
riverctl map normal Super Q spawn "$HOME/.config/river/init"

riverctl map normal Super W close
riverctl map normal Super+Shift Delete spawn "$HOME/.config/scripts/powermenu.sh"

# needs "Handle" options to be set to ignore in /etc/elogind/logind.conf
riverctl map normal None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"

riverctl map normal None XF86AudioPlay spawn "playerctl play-pause"
riverctl map normal None XF86AudioPause spawn "playerctl play-pause"
riverctl map normal None XF86AudioPrev spawn "playerctl previous"
riverctl map normal None XF86AudioNext spawn "playerctl next"

riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl s 5%-"
riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl s 5%+"

riverctl map normal Super P spawn "rofi -show drun"
riverctl map normal Super R spawn "rofi -show run"
riverctl map normal Super Return spawn "alacritty"

riverctl map normal None Print spawn "grim $HOME/Images/Screenshots/$(date +%Y-%m-%dT%H-%M-%S%z).jpg && notify-send -a grim Screenshot 'Saved as $(date +%Y-%m-%dT%H-%M-%S%z).jpg'"
riverctl map normal Super Print spawn "$HOME/.config/scripts/rofi-grim.sh -c 74C7EC"
riverctl map normal Super+Shift Print spawn "$HOME/.config/scripts/rofi-wf-recorder.sh -c 74C7EC"
riverctl map normal Super I spawn "$HOME/.config/scripts/images.sh"
riverctl map normal Super V spawn "$HOME/.config/scripts/videos.sh"

# workspaces/tags
tagnum=9
for i in "$(seq 1 "$tagnum")"; do
	tags=$((1 << ($i - 1)))

	# Super+[1-9] to focus tag [0-8]
	riverctl map normal Super "$i" set-focused-tags $tags

	# Super+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal Super+Shift "$i" set-view-tags $tags

	# Super+Control+[1-9] to toggle focus of tag [0-8]
	riverctl map normal Super+Control "$i" toggle-focused-tags $tags

	# Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << $tagnum) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super F toggle-fullscreen
riverctl map normal Super T toggle-float

# scratchpads
obsidian_scratchpad=$((1 << $tagnum))
keepass_scratchpad=$((2 << $tagnum))

# Toggle the scratchpad tags
riverctl map normal Super+Shift O toggle-focused-tags $obsidian_scratchpad
riverctl map normal Super+Shift P toggle-focused-tags $keepass_scratchpad

# Set spawn tagmask to ensure new windows don"t have the scratchpad tag unless
# explicitly set.
all_but_scratch_tags=$((((1 << $tagnum) - 1) ^ $obsidian_scratchpad))
riverctl spawn-tagmask $all_but_scratch_tags

# resizing
riverctl declare-mode resize
riverctl map normal Super+Shift R enter-mode resize
riverctl map resize None Escape enter-mode normal
riverctl map resize None Return enter-mode normal

riverctl map resize Super+Shift H resize horizontal -50
riverctl map resize Super+Shift J resize vertical 50
riverctl map resize Super+Shift K resize vertical -50
riverctl map resize Super+Shift L resize horizontal 50

# move views
riverctl map resize None H move left 50
riverctl map resize None J move down 50
riverctl map resize None K move up 50
riverctl map resize None L move right 50

# controls windows with the cursor
riverctl map-pointer resize None BTN_LEFT move-view
riverctl map-pointer resize None BTN_RIGHT resize-view

# snap views to screen edges
riverctl map resize Super+Control H snap left
riverctl map resize Super+Control J snap down
riverctl map resize Super+Control K snap up
riverctl map resize Super+Control L snap right

# focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# bump the focused view to the top of the layout stack
riverctl map normal Super Space zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.02"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.02"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# config ###################################################################

riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 0
riverctl hide-cursor when-typing disabled
riverctl set-cursor-warp on-focus-change

# Set background and border color
riverctl background-color 0x002b36ff
riverctl border-color-focused 0x74c7ecff
riverctl border-color-unfocused 0x1e1e2eff

# Rules
riverctl rule-add -app-id "org.keepassxc.KeePassXC" tags $keepass_scratchpad
riverctl rule-add -app-id obsidian tags $obsidian_scratchpad
riverctl rule-add -app-id imv float
riverctl rule-add -app-id mpv float
riverctl rule-add ssd

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-location left -main-ratio 0.55 &

# startup
if [ ! "$(pgrep "pipewire")" ]; then
	pipewire &
	wireplumber &
	pipewire-pulse &
fi

if [ ! "$(pgrep "polkit-gnome")" ]; then
	/usr/libexec/polkit-gnome-authentication-agent-1 &
fi

pkill "wbg"
pkill "mako"
pkill "ags"
pkill "blueman-applet"
pkill "mpd"
pkill "syncthing"
pkill "udiskie"

wbg "$HOME"/Images/Wallpapers/bocchi-vending.png &
mako &
ags &
blueman-applet &
/usr/bin/syncthing serve --no-browser --logfile=default &
udiskie --automount --notify &

if [ ! "$(pgrep "keepassxc")" ]; then
	keepassxc &
fi

if [ ! "$(pgrep "obsidian")" ]; then
	flatpak run md.obsidian.Obsidian &
fi
